### ISSUE TITLE
Adding a log message section for the validation errors.

### ISSUE THREAD

**Issue by mirashanouda** [mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects#15]

**Comment by AhmedEssam78** [comment]
There are logical errors in the part of range validation before reaching the log message terminal.

**Comment by AhmedEssam78** [comment]
Implemented the log message terminal with displaying the range errors independently.

**Comment by AhmedEssam78** [comment]
Question about lower and upper multiplicity

**Comment by AhmedEssam78** [comment]
Fixed..
