### ISSUE TITLE
The configurator does not save the values edited by the user in the gui

### ISSUE THREAD

**Issue by nada-dev** [mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects#33]

**Comment by mirashanouda** [comment]
Duplicate of https://github.com/mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects/issues/35

**Comment by mirashanouda** [comment]
Duplicate of https://github.com/mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects/issues/35
