### ISSUE TITLE
Writing the dynamic code of the generator

### ISSUE THREAD

**Issue by mariam606** [mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects#37]
This includes:
1- Parsing the ARXML
2- Instantiating objects

Subtasks will be added in the comments.

**Comment by mirashanouda** [comment]
Some conflicts in the naming conversion needs to be resolved: 
* ImmediateTxconfEnabled => ImmediateTxConfEnabled
* Some pointers to other containers need NOT to start with CanNm like: 
    * CanNmPnInfo => PnInfo
    * CanNmChannelConfig => ChannelConfig
* semicolon is missing after each sub-container.

**Comment by mirashanouda** [comment]
* The above changes wese resloved. 
* The second point was resloved by renaming the member containers to start with c_CanNm<container name>

**Comment by mirashanouda** [comment]
Initial implementation of the ARXML conversion: https://colab.research.google.com/drive/1GDmr_-BIyUxwRYcxVbf0DO_rePxDNBTK#scrollTo=fdwRtYo5eQ_x

**Comment by mirashanouda** [comment]
Final conversion script is merged in the Generator branch.
